### ISSUE TITLE
is this package using UIWebView?

### ISSUE THREAD

**Issue by girish54321** [socrypto/react-native-highcharts-wrapper#3]
is this package using UIWebView
because apple is not accepting app using **UIWebView**

**Comment by Enoinoo** [comment]
This package is using WebView and ios gives an error "can't open url". However adding `originWhitelist={["file://"]}` to `<ChartView>` solved the problem for me

**Comment by socrypto** [comment]
Closing as this is an issue with WebView rather than this package. 

All props are forwarded onto the `ChartView` component so the above is a solution (thanks @Enoinoo) and there will be other possible ways too dependant on the case. As for this component I prefer to leave it up to the user on how to handle it so will not be adding it to the component source code.

**Comment by girish54321** [comment]
ok @socrypto
